import * as _54 from "./abci/types";
import * as _55 from "./crypto/keys";
import * as _56 from "./crypto/proof";
import * as _57 from "./libs/bits/types";
import * as _58 from "./p2p/types";
import * as _59 from "./types/block";
import * as _60 from "./types/evidence";
import * as _61 from "./types/params";
import * as _62 from "./types/types";
import * as _63 from "./types/validator";
import * as _64 from "./version/types";
export declare namespace tendermint {
    const abci: {
        checkTxTypeFromJSON(object: any): _54.CheckTxType;
        checkTxTypeToJSON(object: _54.CheckTxType): string;
        responseOfferSnapshot_ResultFromJSON(object: any): _54.ResponseOfferSnapshot_Result;
        responseOfferSnapshot_ResultToJSON(object: _54.ResponseOfferSnapshot_Result): string;
        responseApplySnapshotChunk_ResultFromJSON(object: any): _54.ResponseApplySnapshotChunk_Result;
        responseApplySnapshotChunk_ResultToJSON(object: _54.ResponseApplySnapshotChunk_Result): string;
        evidenceTypeFromJSON(object: any): _54.EvidenceType;
        evidenceTypeToJSON(object: _54.EvidenceType): string;
        CheckTxType: typeof _54.CheckTxType;
        CheckTxTypeSDKType: typeof _54.CheckTxType;
        CheckTxTypeAmino: typeof _54.CheckTxType;
        ResponseOfferSnapshot_Result: typeof _54.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultSDKType: typeof _54.ResponseOfferSnapshot_Result;
        ResponseOfferSnapshot_ResultAmino: typeof _54.ResponseOfferSnapshot_Result;
        ResponseApplySnapshotChunk_Result: typeof _54.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultSDKType: typeof _54.ResponseApplySnapshotChunk_Result;
        ResponseApplySnapshotChunk_ResultAmino: typeof _54.ResponseApplySnapshotChunk_Result;
        EvidenceType: typeof _54.EvidenceType;
        EvidenceTypeSDKType: typeof _54.EvidenceType;
        EvidenceTypeAmino: typeof _54.EvidenceType;
        Request: {
            encode(message: _54.Request, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Request;
            fromPartial(object: any): _54.Request;
            fromAmino(object: _54.RequestAmino): _54.Request;
            toAmino(message: _54.Request): _54.RequestAmino;
            fromAminoMsg(object: _54.RequestAminoMsg): _54.Request;
            fromProtoMsg(message: _54.RequestProtoMsg): _54.Request;
            toProto(message: _54.Request): Uint8Array;
            toProtoMsg(message: _54.Request): _54.RequestProtoMsg;
        };
        RequestEcho: {
            encode(message: _54.RequestEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestEcho;
            fromPartial(object: any): _54.RequestEcho;
            fromAmino(object: _54.RequestEchoAmino): _54.RequestEcho;
            toAmino(message: _54.RequestEcho): _54.RequestEchoAmino;
            fromAminoMsg(object: _54.RequestEchoAminoMsg): _54.RequestEcho;
            fromProtoMsg(message: _54.RequestEchoProtoMsg): _54.RequestEcho;
            toProto(message: _54.RequestEcho): Uint8Array;
            toProtoMsg(message: _54.RequestEcho): _54.RequestEchoProtoMsg;
        };
        RequestFlush: {
            encode(_: _54.RequestFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestFlush;
            fromPartial(_: any): _54.RequestFlush;
            fromAmino(_: _54.RequestFlushAmino): _54.RequestFlush;
            toAmino(_: _54.RequestFlush): _54.RequestFlushAmino;
            fromAminoMsg(object: _54.RequestFlushAminoMsg): _54.RequestFlush;
            fromProtoMsg(message: _54.RequestFlushProtoMsg): _54.RequestFlush;
            toProto(message: _54.RequestFlush): Uint8Array;
            toProtoMsg(message: _54.RequestFlush): _54.RequestFlushProtoMsg;
        };
        RequestInfo: {
            encode(message: _54.RequestInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestInfo;
            fromPartial(object: any): _54.RequestInfo;
            fromAmino(object: _54.RequestInfoAmino): _54.RequestInfo;
            toAmino(message: _54.RequestInfo): _54.RequestInfoAmino;
            fromAminoMsg(object: _54.RequestInfoAminoMsg): _54.RequestInfo;
            fromProtoMsg(message: _54.RequestInfoProtoMsg): _54.RequestInfo;
            toProto(message: _54.RequestInfo): Uint8Array;
            toProtoMsg(message: _54.RequestInfo): _54.RequestInfoProtoMsg;
        };
        RequestSetOption: {
            encode(message: _54.RequestSetOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestSetOption;
            fromPartial(object: any): _54.RequestSetOption;
            fromAmino(object: _54.RequestSetOptionAmino): _54.RequestSetOption;
            toAmino(message: _54.RequestSetOption): _54.RequestSetOptionAmino;
            fromAminoMsg(object: _54.RequestSetOptionAminoMsg): _54.RequestSetOption;
            fromProtoMsg(message: _54.RequestSetOptionProtoMsg): _54.RequestSetOption;
            toProto(message: _54.RequestSetOption): Uint8Array;
            toProtoMsg(message: _54.RequestSetOption): _54.RequestSetOptionProtoMsg;
        };
        RequestInitChain: {
            encode(message: _54.RequestInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestInitChain;
            fromPartial(object: any): _54.RequestInitChain;
            fromAmino(object: _54.RequestInitChainAmino): _54.RequestInitChain;
            toAmino(message: _54.RequestInitChain): _54.RequestInitChainAmino;
            fromAminoMsg(object: _54.RequestInitChainAminoMsg): _54.RequestInitChain;
            fromProtoMsg(message: _54.RequestInitChainProtoMsg): _54.RequestInitChain;
            toProto(message: _54.RequestInitChain): Uint8Array;
            toProtoMsg(message: _54.RequestInitChain): _54.RequestInitChainProtoMsg;
        };
        RequestQuery: {
            encode(message: _54.RequestQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestQuery;
            fromPartial(object: any): _54.RequestQuery;
            fromAmino(object: _54.RequestQueryAmino): _54.RequestQuery;
            toAmino(message: _54.RequestQuery): _54.RequestQueryAmino;
            fromAminoMsg(object: _54.RequestQueryAminoMsg): _54.RequestQuery;
            fromProtoMsg(message: _54.RequestQueryProtoMsg): _54.RequestQuery;
            toProto(message: _54.RequestQuery): Uint8Array;
            toProtoMsg(message: _54.RequestQuery): _54.RequestQueryProtoMsg;
        };
        RequestBeginBlock: {
            encode(message: _54.RequestBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestBeginBlock;
            fromPartial(object: any): _54.RequestBeginBlock;
            fromAmino(object: _54.RequestBeginBlockAmino): _54.RequestBeginBlock;
            toAmino(message: _54.RequestBeginBlock): _54.RequestBeginBlockAmino;
            fromAminoMsg(object: _54.RequestBeginBlockAminoMsg): _54.RequestBeginBlock;
            fromProtoMsg(message: _54.RequestBeginBlockProtoMsg): _54.RequestBeginBlock;
            toProto(message: _54.RequestBeginBlock): Uint8Array;
            toProtoMsg(message: _54.RequestBeginBlock): _54.RequestBeginBlockProtoMsg;
        };
        RequestCheckTx: {
            encode(message: _54.RequestCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestCheckTx;
            fromPartial(object: any): _54.RequestCheckTx;
            fromAmino(object: _54.RequestCheckTxAmino): _54.RequestCheckTx;
            toAmino(message: _54.RequestCheckTx): _54.RequestCheckTxAmino;
            fromAminoMsg(object: _54.RequestCheckTxAminoMsg): _54.RequestCheckTx;
            fromProtoMsg(message: _54.RequestCheckTxProtoMsg): _54.RequestCheckTx;
            toProto(message: _54.RequestCheckTx): Uint8Array;
            toProtoMsg(message: _54.RequestCheckTx): _54.RequestCheckTxProtoMsg;
        };
        RequestDeliverTx: {
            encode(message: _54.RequestDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestDeliverTx;
            fromPartial(object: any): _54.RequestDeliverTx;
            fromAmino(object: _54.RequestDeliverTxAmino): _54.RequestDeliverTx;
            toAmino(message: _54.RequestDeliverTx): _54.RequestDeliverTxAmino;
            fromAminoMsg(object: _54.RequestDeliverTxAminoMsg): _54.RequestDeliverTx;
            fromProtoMsg(message: _54.RequestDeliverTxProtoMsg): _54.RequestDeliverTx;
            toProto(message: _54.RequestDeliverTx): Uint8Array;
            toProtoMsg(message: _54.RequestDeliverTx): _54.RequestDeliverTxProtoMsg;
        };
        RequestEndBlock: {
            encode(message: _54.RequestEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestEndBlock;
            fromPartial(object: any): _54.RequestEndBlock;
            fromAmino(object: _54.RequestEndBlockAmino): _54.RequestEndBlock;
            toAmino(message: _54.RequestEndBlock): _54.RequestEndBlockAmino;
            fromAminoMsg(object: _54.RequestEndBlockAminoMsg): _54.RequestEndBlock;
            fromProtoMsg(message: _54.RequestEndBlockProtoMsg): _54.RequestEndBlock;
            toProto(message: _54.RequestEndBlock): Uint8Array;
            toProtoMsg(message: _54.RequestEndBlock): _54.RequestEndBlockProtoMsg;
        };
        RequestCommit: {
            encode(_: _54.RequestCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestCommit;
            fromPartial(_: any): _54.RequestCommit;
            fromAmino(_: _54.RequestCommitAmino): _54.RequestCommit;
            toAmino(_: _54.RequestCommit): _54.RequestCommitAmino;
            fromAminoMsg(object: _54.RequestCommitAminoMsg): _54.RequestCommit;
            fromProtoMsg(message: _54.RequestCommitProtoMsg): _54.RequestCommit;
            toProto(message: _54.RequestCommit): Uint8Array;
            toProtoMsg(message: _54.RequestCommit): _54.RequestCommitProtoMsg;
        };
        RequestListSnapshots: {
            encode(_: _54.RequestListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestListSnapshots;
            fromPartial(_: any): _54.RequestListSnapshots;
            fromAmino(_: _54.RequestListSnapshotsAmino): _54.RequestListSnapshots;
            toAmino(_: _54.RequestListSnapshots): _54.RequestListSnapshotsAmino;
            fromAminoMsg(object: _54.RequestListSnapshotsAminoMsg): _54.RequestListSnapshots;
            fromProtoMsg(message: _54.RequestListSnapshotsProtoMsg): _54.RequestListSnapshots;
            toProto(message: _54.RequestListSnapshots): Uint8Array;
            toProtoMsg(message: _54.RequestListSnapshots): _54.RequestListSnapshotsProtoMsg;
        };
        RequestOfferSnapshot: {
            encode(message: _54.RequestOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestOfferSnapshot;
            fromPartial(object: any): _54.RequestOfferSnapshot;
            fromAmino(object: _54.RequestOfferSnapshotAmino): _54.RequestOfferSnapshot;
            toAmino(message: _54.RequestOfferSnapshot): _54.RequestOfferSnapshotAmino;
            fromAminoMsg(object: _54.RequestOfferSnapshotAminoMsg): _54.RequestOfferSnapshot;
            fromProtoMsg(message: _54.RequestOfferSnapshotProtoMsg): _54.RequestOfferSnapshot;
            toProto(message: _54.RequestOfferSnapshot): Uint8Array;
            toProtoMsg(message: _54.RequestOfferSnapshot): _54.RequestOfferSnapshotProtoMsg;
        };
        RequestLoadSnapshotChunk: {
            encode(message: _54.RequestLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestLoadSnapshotChunk;
            fromPartial(object: any): _54.RequestLoadSnapshotChunk;
            fromAmino(object: _54.RequestLoadSnapshotChunkAmino): _54.RequestLoadSnapshotChunk;
            toAmino(message: _54.RequestLoadSnapshotChunk): _54.RequestLoadSnapshotChunkAmino;
            fromAminoMsg(object: _54.RequestLoadSnapshotChunkAminoMsg): _54.RequestLoadSnapshotChunk;
            fromProtoMsg(message: _54.RequestLoadSnapshotChunkProtoMsg): _54.RequestLoadSnapshotChunk;
            toProto(message: _54.RequestLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _54.RequestLoadSnapshotChunk): _54.RequestLoadSnapshotChunkProtoMsg;
        };
        RequestApplySnapshotChunk: {
            encode(message: _54.RequestApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.RequestApplySnapshotChunk;
            fromPartial(object: any): _54.RequestApplySnapshotChunk;
            fromAmino(object: _54.RequestApplySnapshotChunkAmino): _54.RequestApplySnapshotChunk;
            toAmino(message: _54.RequestApplySnapshotChunk): _54.RequestApplySnapshotChunkAmino;
            fromAminoMsg(object: _54.RequestApplySnapshotChunkAminoMsg): _54.RequestApplySnapshotChunk;
            fromProtoMsg(message: _54.RequestApplySnapshotChunkProtoMsg): _54.RequestApplySnapshotChunk;
            toProto(message: _54.RequestApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _54.RequestApplySnapshotChunk): _54.RequestApplySnapshotChunkProtoMsg;
        };
        Response: {
            encode(message: _54.Response, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Response;
            fromPartial(object: any): _54.Response;
            fromAmino(object: _54.ResponseAmino): _54.Response;
            toAmino(message: _54.Response): _54.ResponseAmino;
            fromAminoMsg(object: _54.ResponseAminoMsg): _54.Response;
            fromProtoMsg(message: _54.ResponseProtoMsg): _54.Response;
            toProto(message: _54.Response): Uint8Array;
            toProtoMsg(message: _54.Response): _54.ResponseProtoMsg;
        };
        ResponseException: {
            encode(message: _54.ResponseException, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseException;
            fromPartial(object: any): _54.ResponseException;
            fromAmino(object: _54.ResponseExceptionAmino): _54.ResponseException;
            toAmino(message: _54.ResponseException): _54.ResponseExceptionAmino;
            fromAminoMsg(object: _54.ResponseExceptionAminoMsg): _54.ResponseException;
            fromProtoMsg(message: _54.ResponseExceptionProtoMsg): _54.ResponseException;
            toProto(message: _54.ResponseException): Uint8Array;
            toProtoMsg(message: _54.ResponseException): _54.ResponseExceptionProtoMsg;
        };
        ResponseEcho: {
            encode(message: _54.ResponseEcho, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseEcho;
            fromPartial(object: any): _54.ResponseEcho;
            fromAmino(object: _54.ResponseEchoAmino): _54.ResponseEcho;
            toAmino(message: _54.ResponseEcho): _54.ResponseEchoAmino;
            fromAminoMsg(object: _54.ResponseEchoAminoMsg): _54.ResponseEcho;
            fromProtoMsg(message: _54.ResponseEchoProtoMsg): _54.ResponseEcho;
            toProto(message: _54.ResponseEcho): Uint8Array;
            toProtoMsg(message: _54.ResponseEcho): _54.ResponseEchoProtoMsg;
        };
        ResponseFlush: {
            encode(_: _54.ResponseFlush, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseFlush;
            fromPartial(_: any): _54.ResponseFlush;
            fromAmino(_: _54.ResponseFlushAmino): _54.ResponseFlush;
            toAmino(_: _54.ResponseFlush): _54.ResponseFlushAmino;
            fromAminoMsg(object: _54.ResponseFlushAminoMsg): _54.ResponseFlush;
            fromProtoMsg(message: _54.ResponseFlushProtoMsg): _54.ResponseFlush;
            toProto(message: _54.ResponseFlush): Uint8Array;
            toProtoMsg(message: _54.ResponseFlush): _54.ResponseFlushProtoMsg;
        };
        ResponseInfo: {
            encode(message: _54.ResponseInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseInfo;
            fromPartial(object: any): _54.ResponseInfo;
            fromAmino(object: _54.ResponseInfoAmino): _54.ResponseInfo;
            toAmino(message: _54.ResponseInfo): _54.ResponseInfoAmino;
            fromAminoMsg(object: _54.ResponseInfoAminoMsg): _54.ResponseInfo;
            fromProtoMsg(message: _54.ResponseInfoProtoMsg): _54.ResponseInfo;
            toProto(message: _54.ResponseInfo): Uint8Array;
            toProtoMsg(message: _54.ResponseInfo): _54.ResponseInfoProtoMsg;
        };
        ResponseSetOption: {
            encode(message: _54.ResponseSetOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseSetOption;
            fromPartial(object: any): _54.ResponseSetOption;
            fromAmino(object: _54.ResponseSetOptionAmino): _54.ResponseSetOption;
            toAmino(message: _54.ResponseSetOption): _54.ResponseSetOptionAmino;
            fromAminoMsg(object: _54.ResponseSetOptionAminoMsg): _54.ResponseSetOption;
            fromProtoMsg(message: _54.ResponseSetOptionProtoMsg): _54.ResponseSetOption;
            toProto(message: _54.ResponseSetOption): Uint8Array;
            toProtoMsg(message: _54.ResponseSetOption): _54.ResponseSetOptionProtoMsg;
        };
        ResponseInitChain: {
            encode(message: _54.ResponseInitChain, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseInitChain;
            fromPartial(object: any): _54.ResponseInitChain;
            fromAmino(object: _54.ResponseInitChainAmino): _54.ResponseInitChain;
            toAmino(message: _54.ResponseInitChain): _54.ResponseInitChainAmino;
            fromAminoMsg(object: _54.ResponseInitChainAminoMsg): _54.ResponseInitChain;
            fromProtoMsg(message: _54.ResponseInitChainProtoMsg): _54.ResponseInitChain;
            toProto(message: _54.ResponseInitChain): Uint8Array;
            toProtoMsg(message: _54.ResponseInitChain): _54.ResponseInitChainProtoMsg;
        };
        ResponseQuery: {
            encode(message: _54.ResponseQuery, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseQuery;
            fromPartial(object: any): _54.ResponseQuery;
            fromAmino(object: _54.ResponseQueryAmino): _54.ResponseQuery;
            toAmino(message: _54.ResponseQuery): _54.ResponseQueryAmino;
            fromAminoMsg(object: _54.ResponseQueryAminoMsg): _54.ResponseQuery;
            fromProtoMsg(message: _54.ResponseQueryProtoMsg): _54.ResponseQuery;
            toProto(message: _54.ResponseQuery): Uint8Array;
            toProtoMsg(message: _54.ResponseQuery): _54.ResponseQueryProtoMsg;
        };
        ResponseBeginBlock: {
            encode(message: _54.ResponseBeginBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseBeginBlock;
            fromPartial(object: any): _54.ResponseBeginBlock;
            fromAmino(object: _54.ResponseBeginBlockAmino): _54.ResponseBeginBlock;
            toAmino(message: _54.ResponseBeginBlock): _54.ResponseBeginBlockAmino;
            fromAminoMsg(object: _54.ResponseBeginBlockAminoMsg): _54.ResponseBeginBlock;
            fromProtoMsg(message: _54.ResponseBeginBlockProtoMsg): _54.ResponseBeginBlock;
            toProto(message: _54.ResponseBeginBlock): Uint8Array;
            toProtoMsg(message: _54.ResponseBeginBlock): _54.ResponseBeginBlockProtoMsg;
        };
        ResponseCheckTx: {
            encode(message: _54.ResponseCheckTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseCheckTx;
            fromPartial(object: any): _54.ResponseCheckTx;
            fromAmino(object: _54.ResponseCheckTxAmino): _54.ResponseCheckTx;
            toAmino(message: _54.ResponseCheckTx): _54.ResponseCheckTxAmino;
            fromAminoMsg(object: _54.ResponseCheckTxAminoMsg): _54.ResponseCheckTx;
            fromProtoMsg(message: _54.ResponseCheckTxProtoMsg): _54.ResponseCheckTx;
            toProto(message: _54.ResponseCheckTx): Uint8Array;
            toProtoMsg(message: _54.ResponseCheckTx): _54.ResponseCheckTxProtoMsg;
        };
        ResponseDeliverTx: {
            encode(message: _54.ResponseDeliverTx, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseDeliverTx;
            fromPartial(object: any): _54.ResponseDeliverTx;
            fromAmino(object: _54.ResponseDeliverTxAmino): _54.ResponseDeliverTx;
            toAmino(message: _54.ResponseDeliverTx): _54.ResponseDeliverTxAmino;
            fromAminoMsg(object: _54.ResponseDeliverTxAminoMsg): _54.ResponseDeliverTx;
            fromProtoMsg(message: _54.ResponseDeliverTxProtoMsg): _54.ResponseDeliverTx;
            toProto(message: _54.ResponseDeliverTx): Uint8Array;
            toProtoMsg(message: _54.ResponseDeliverTx): _54.ResponseDeliverTxProtoMsg;
        };
        ResponseEndBlock: {
            encode(message: _54.ResponseEndBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseEndBlock;
            fromPartial(object: any): _54.ResponseEndBlock;
            fromAmino(object: _54.ResponseEndBlockAmino): _54.ResponseEndBlock;
            toAmino(message: _54.ResponseEndBlock): _54.ResponseEndBlockAmino;
            fromAminoMsg(object: _54.ResponseEndBlockAminoMsg): _54.ResponseEndBlock;
            fromProtoMsg(message: _54.ResponseEndBlockProtoMsg): _54.ResponseEndBlock;
            toProto(message: _54.ResponseEndBlock): Uint8Array;
            toProtoMsg(message: _54.ResponseEndBlock): _54.ResponseEndBlockProtoMsg;
        };
        ResponseCommit: {
            encode(message: _54.ResponseCommit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseCommit;
            fromPartial(object: any): _54.ResponseCommit;
            fromAmino(object: _54.ResponseCommitAmino): _54.ResponseCommit;
            toAmino(message: _54.ResponseCommit): _54.ResponseCommitAmino;
            fromAminoMsg(object: _54.ResponseCommitAminoMsg): _54.ResponseCommit;
            fromProtoMsg(message: _54.ResponseCommitProtoMsg): _54.ResponseCommit;
            toProto(message: _54.ResponseCommit): Uint8Array;
            toProtoMsg(message: _54.ResponseCommit): _54.ResponseCommitProtoMsg;
        };
        ResponseListSnapshots: {
            encode(message: _54.ResponseListSnapshots, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseListSnapshots;
            fromPartial(object: any): _54.ResponseListSnapshots;
            fromAmino(object: _54.ResponseListSnapshotsAmino): _54.ResponseListSnapshots;
            toAmino(message: _54.ResponseListSnapshots): _54.ResponseListSnapshotsAmino;
            fromAminoMsg(object: _54.ResponseListSnapshotsAminoMsg): _54.ResponseListSnapshots;
            fromProtoMsg(message: _54.ResponseListSnapshotsProtoMsg): _54.ResponseListSnapshots;
            toProto(message: _54.ResponseListSnapshots): Uint8Array;
            toProtoMsg(message: _54.ResponseListSnapshots): _54.ResponseListSnapshotsProtoMsg;
        };
        ResponseOfferSnapshot: {
            encode(message: _54.ResponseOfferSnapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseOfferSnapshot;
            fromPartial(object: any): _54.ResponseOfferSnapshot;
            fromAmino(object: _54.ResponseOfferSnapshotAmino): _54.ResponseOfferSnapshot;
            toAmino(message: _54.ResponseOfferSnapshot): _54.ResponseOfferSnapshotAmino;
            fromAminoMsg(object: _54.ResponseOfferSnapshotAminoMsg): _54.ResponseOfferSnapshot;
            fromProtoMsg(message: _54.ResponseOfferSnapshotProtoMsg): _54.ResponseOfferSnapshot;
            toProto(message: _54.ResponseOfferSnapshot): Uint8Array;
            toProtoMsg(message: _54.ResponseOfferSnapshot): _54.ResponseOfferSnapshotProtoMsg;
        };
        ResponseLoadSnapshotChunk: {
            encode(message: _54.ResponseLoadSnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseLoadSnapshotChunk;
            fromPartial(object: any): _54.ResponseLoadSnapshotChunk;
            fromAmino(object: _54.ResponseLoadSnapshotChunkAmino): _54.ResponseLoadSnapshotChunk;
            toAmino(message: _54.ResponseLoadSnapshotChunk): _54.ResponseLoadSnapshotChunkAmino;
            fromAminoMsg(object: _54.ResponseLoadSnapshotChunkAminoMsg): _54.ResponseLoadSnapshotChunk;
            fromProtoMsg(message: _54.ResponseLoadSnapshotChunkProtoMsg): _54.ResponseLoadSnapshotChunk;
            toProto(message: _54.ResponseLoadSnapshotChunk): Uint8Array;
            toProtoMsg(message: _54.ResponseLoadSnapshotChunk): _54.ResponseLoadSnapshotChunkProtoMsg;
        };
        ResponseApplySnapshotChunk: {
            encode(message: _54.ResponseApplySnapshotChunk, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ResponseApplySnapshotChunk;
            fromPartial(object: any): _54.ResponseApplySnapshotChunk;
            fromAmino(object: _54.ResponseApplySnapshotChunkAmino): _54.ResponseApplySnapshotChunk;
            toAmino(message: _54.ResponseApplySnapshotChunk): _54.ResponseApplySnapshotChunkAmino;
            fromAminoMsg(object: _54.ResponseApplySnapshotChunkAminoMsg): _54.ResponseApplySnapshotChunk;
            fromProtoMsg(message: _54.ResponseApplySnapshotChunkProtoMsg): _54.ResponseApplySnapshotChunk;
            toProto(message: _54.ResponseApplySnapshotChunk): Uint8Array;
            toProtoMsg(message: _54.ResponseApplySnapshotChunk): _54.ResponseApplySnapshotChunkProtoMsg;
        };
        ConsensusParams: {
            encode(message: _54.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ConsensusParams;
            fromPartial(object: any): _54.ConsensusParams;
            fromAmino(object: _54.ConsensusParamsAmino): _54.ConsensusParams;
            toAmino(message: _54.ConsensusParams): _54.ConsensusParamsAmino;
            fromAminoMsg(object: _54.ConsensusParamsAminoMsg): _54.ConsensusParams;
            fromProtoMsg(message: _54.ConsensusParamsProtoMsg): _54.ConsensusParams;
            toProto(message: _54.ConsensusParams): Uint8Array;
            toProtoMsg(message: _54.ConsensusParams): _54.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            encode(message: _54.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.BlockParams;
            fromPartial(object: any): _54.BlockParams;
            fromAmino(object: _54.BlockParamsAmino): _54.BlockParams;
            toAmino(message: _54.BlockParams): _54.BlockParamsAmino;
            fromAminoMsg(object: _54.BlockParamsAminoMsg): _54.BlockParams;
            fromProtoMsg(message: _54.BlockParamsProtoMsg): _54.BlockParams;
            toProto(message: _54.BlockParams): Uint8Array;
            toProtoMsg(message: _54.BlockParams): _54.BlockParamsProtoMsg;
        };
        LastCommitInfo: {
            encode(message: _54.LastCommitInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.LastCommitInfo;
            fromPartial(object: any): _54.LastCommitInfo;
            fromAmino(object: _54.LastCommitInfoAmino): _54.LastCommitInfo;
            toAmino(message: _54.LastCommitInfo): _54.LastCommitInfoAmino;
            fromAminoMsg(object: _54.LastCommitInfoAminoMsg): _54.LastCommitInfo;
            fromProtoMsg(message: _54.LastCommitInfoProtoMsg): _54.LastCommitInfo;
            toProto(message: _54.LastCommitInfo): Uint8Array;
            toProtoMsg(message: _54.LastCommitInfo): _54.LastCommitInfoProtoMsg;
        };
        Event: {
            encode(message: _54.Event, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Event;
            fromPartial(object: any): _54.Event;
            fromAmino(object: _54.EventAmino): _54.Event;
            toAmino(message: _54.Event): _54.EventAmino;
            fromAminoMsg(object: _54.EventAminoMsg): _54.Event;
            fromProtoMsg(message: _54.EventProtoMsg): _54.Event;
            toProto(message: _54.Event): Uint8Array;
            toProtoMsg(message: _54.Event): _54.EventProtoMsg;
        };
        EventAttribute: {
            encode(message: _54.EventAttribute, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.EventAttribute;
            fromPartial(object: any): _54.EventAttribute;
            fromAmino(object: _54.EventAttributeAmino): _54.EventAttribute;
            toAmino(message: _54.EventAttribute): _54.EventAttributeAmino;
            fromAminoMsg(object: _54.EventAttributeAminoMsg): _54.EventAttribute;
            fromProtoMsg(message: _54.EventAttributeProtoMsg): _54.EventAttribute;
            toProto(message: _54.EventAttribute): Uint8Array;
            toProtoMsg(message: _54.EventAttribute): _54.EventAttributeProtoMsg;
        };
        TxResult: {
            encode(message: _54.TxResult, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.TxResult;
            fromPartial(object: any): _54.TxResult;
            fromAmino(object: _54.TxResultAmino): _54.TxResult;
            toAmino(message: _54.TxResult): _54.TxResultAmino;
            fromAminoMsg(object: _54.TxResultAminoMsg): _54.TxResult;
            fromProtoMsg(message: _54.TxResultProtoMsg): _54.TxResult;
            toProto(message: _54.TxResult): Uint8Array;
            toProtoMsg(message: _54.TxResult): _54.TxResultProtoMsg;
        };
        Validator: {
            encode(message: _54.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Validator;
            fromPartial(object: any): _54.Validator;
            fromAmino(object: _54.ValidatorAmino): _54.Validator;
            toAmino(message: _54.Validator): _54.ValidatorAmino;
            fromAminoMsg(object: _54.ValidatorAminoMsg): _54.Validator;
            fromProtoMsg(message: _54.ValidatorProtoMsg): _54.Validator;
            toProto(message: _54.Validator): Uint8Array;
            toProtoMsg(message: _54.Validator): _54.ValidatorProtoMsg;
        };
        ValidatorUpdate: {
            encode(message: _54.ValidatorUpdate, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.ValidatorUpdate;
            fromPartial(object: any): _54.ValidatorUpdate;
            fromAmino(object: _54.ValidatorUpdateAmino): _54.ValidatorUpdate;
            toAmino(message: _54.ValidatorUpdate): _54.ValidatorUpdateAmino;
            fromAminoMsg(object: _54.ValidatorUpdateAminoMsg): _54.ValidatorUpdate;
            fromProtoMsg(message: _54.ValidatorUpdateProtoMsg): _54.ValidatorUpdate;
            toProto(message: _54.ValidatorUpdate): Uint8Array;
            toProtoMsg(message: _54.ValidatorUpdate): _54.ValidatorUpdateProtoMsg;
        };
        VoteInfo: {
            encode(message: _54.VoteInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.VoteInfo;
            fromPartial(object: any): _54.VoteInfo;
            fromAmino(object: _54.VoteInfoAmino): _54.VoteInfo;
            toAmino(message: _54.VoteInfo): _54.VoteInfoAmino;
            fromAminoMsg(object: _54.VoteInfoAminoMsg): _54.VoteInfo;
            fromProtoMsg(message: _54.VoteInfoProtoMsg): _54.VoteInfo;
            toProto(message: _54.VoteInfo): Uint8Array;
            toProtoMsg(message: _54.VoteInfo): _54.VoteInfoProtoMsg;
        };
        Evidence: {
            encode(message: _54.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Evidence;
            fromPartial(object: any): _54.Evidence;
            fromAmino(object: _54.EvidenceAmino): _54.Evidence;
            toAmino(message: _54.Evidence): _54.EvidenceAmino;
            fromAminoMsg(object: _54.EvidenceAminoMsg): _54.Evidence;
            fromProtoMsg(message: _54.EvidenceProtoMsg): _54.Evidence;
            toProto(message: _54.Evidence): Uint8Array;
            toProtoMsg(message: _54.Evidence): _54.EvidenceProtoMsg;
        };
        Snapshot: {
            encode(message: _54.Snapshot, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _54.Snapshot;
            fromPartial(object: any): _54.Snapshot;
            fromAmino(object: _54.SnapshotAmino): _54.Snapshot;
            toAmino(message: _54.Snapshot): _54.SnapshotAmino;
            fromAminoMsg(object: _54.SnapshotAminoMsg): _54.Snapshot;
            fromProtoMsg(message: _54.SnapshotProtoMsg): _54.Snapshot;
            toProto(message: _54.Snapshot): Uint8Array;
            toProtoMsg(message: _54.Snapshot): _54.SnapshotProtoMsg;
        };
    };
    const crypto: {
        Proof: {
            encode(message: _56.Proof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _56.Proof;
            fromPartial(object: any): _56.Proof;
            fromAmino(object: _56.ProofAmino): _56.Proof;
            toAmino(message: _56.Proof): _56.ProofAmino;
            fromAminoMsg(object: _56.ProofAminoMsg): _56.Proof;
            fromProtoMsg(message: _56.ProofProtoMsg): _56.Proof;
            toProto(message: _56.Proof): Uint8Array;
            toProtoMsg(message: _56.Proof): _56.ProofProtoMsg;
        };
        ValueOp: {
            encode(message: _56.ValueOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _56.ValueOp;
            fromPartial(object: any): _56.ValueOp;
            fromAmino(object: _56.ValueOpAmino): _56.ValueOp;
            toAmino(message: _56.ValueOp): _56.ValueOpAmino;
            fromAminoMsg(object: _56.ValueOpAminoMsg): _56.ValueOp;
            fromProtoMsg(message: _56.ValueOpProtoMsg): _56.ValueOp;
            toProto(message: _56.ValueOp): Uint8Array;
            toProtoMsg(message: _56.ValueOp): _56.ValueOpProtoMsg;
        };
        DominoOp: {
            encode(message: _56.DominoOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _56.DominoOp;
            fromPartial(object: any): _56.DominoOp;
            fromAmino(object: _56.DominoOpAmino): _56.DominoOp;
            toAmino(message: _56.DominoOp): _56.DominoOpAmino;
            fromAminoMsg(object: _56.DominoOpAminoMsg): _56.DominoOp;
            fromProtoMsg(message: _56.DominoOpProtoMsg): _56.DominoOp;
            toProto(message: _56.DominoOp): Uint8Array;
            toProtoMsg(message: _56.DominoOp): _56.DominoOpProtoMsg;
        };
        ProofOp: {
            encode(message: _56.ProofOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _56.ProofOp;
            fromPartial(object: any): _56.ProofOp;
            fromAmino(object: _56.ProofOpAmino): _56.ProofOp;
            toAmino(message: _56.ProofOp): _56.ProofOpAmino;
            fromAminoMsg(object: _56.ProofOpAminoMsg): _56.ProofOp;
            fromProtoMsg(message: _56.ProofOpProtoMsg): _56.ProofOp;
            toProto(message: _56.ProofOp): Uint8Array;
            toProtoMsg(message: _56.ProofOp): _56.ProofOpProtoMsg;
        };
        ProofOps: {
            encode(message: _56.ProofOps, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _56.ProofOps;
            fromPartial(object: any): _56.ProofOps;
            fromAmino(object: _56.ProofOpsAmino): _56.ProofOps;
            toAmino(message: _56.ProofOps): _56.ProofOpsAmino;
            fromAminoMsg(object: _56.ProofOpsAminoMsg): _56.ProofOps;
            fromProtoMsg(message: _56.ProofOpsProtoMsg): _56.ProofOps;
            toProto(message: _56.ProofOps): Uint8Array;
            toProtoMsg(message: _56.ProofOps): _56.ProofOpsProtoMsg;
        };
        PublicKey: {
            encode(message: _55.PublicKey, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _55.PublicKey;
            fromPartial(object: any): _55.PublicKey;
            fromAmino(object: _55.PublicKeyAmino): _55.PublicKey;
            toAmino(message: _55.PublicKey): _55.PublicKeyAmino;
            fromAminoMsg(object: _55.PublicKeyAminoMsg): _55.PublicKey;
            fromProtoMsg(message: _55.PublicKeyProtoMsg): _55.PublicKey;
            toProto(message: _55.PublicKey): Uint8Array;
            toProtoMsg(message: _55.PublicKey): _55.PublicKeyProtoMsg;
        };
    };
    namespace libs {
        const bits: {
            BitArray: {
                encode(message: _57.BitArray, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
                decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _57.BitArray;
                fromPartial(object: any): _57.BitArray;
                fromAmino(object: _57.BitArrayAmino): _57.BitArray;
                toAmino(message: _57.BitArray): _57.BitArrayAmino;
                fromAminoMsg(object: _57.BitArrayAminoMsg): _57.BitArray;
                fromProtoMsg(message: _57.BitArrayProtoMsg): _57.BitArray;
                toProto(message: _57.BitArray): Uint8Array;
                toProtoMsg(message: _57.BitArray): _57.BitArrayProtoMsg;
            };
        };
    }
    const p2p: {
        NetAddress: {
            encode(message: _58.NetAddress, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _58.NetAddress;
            fromPartial(object: any): _58.NetAddress;
            fromAmino(object: _58.NetAddressAmino): _58.NetAddress;
            toAmino(message: _58.NetAddress): _58.NetAddressAmino;
            fromAminoMsg(object: _58.NetAddressAminoMsg): _58.NetAddress;
            fromProtoMsg(message: _58.NetAddressProtoMsg): _58.NetAddress;
            toProto(message: _58.NetAddress): Uint8Array;
            toProtoMsg(message: _58.NetAddress): _58.NetAddressProtoMsg;
        };
        ProtocolVersion: {
            encode(message: _58.ProtocolVersion, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _58.ProtocolVersion;
            fromPartial(object: any): _58.ProtocolVersion;
            fromAmino(object: _58.ProtocolVersionAmino): _58.ProtocolVersion;
            toAmino(message: _58.ProtocolVersion): _58.ProtocolVersionAmino;
            fromAminoMsg(object: _58.ProtocolVersionAminoMsg): _58.ProtocolVersion;
            fromProtoMsg(message: _58.ProtocolVersionProtoMsg): _58.ProtocolVersion;
            toProto(message: _58.ProtocolVersion): Uint8Array;
            toProtoMsg(message: _58.ProtocolVersion): _58.ProtocolVersionProtoMsg;
        };
        DefaultNodeInfo: {
            encode(message: _58.DefaultNodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _58.DefaultNodeInfo;
            fromPartial(object: any): _58.DefaultNodeInfo;
            fromAmino(object: _58.DefaultNodeInfoAmino): _58.DefaultNodeInfo;
            toAmino(message: _58.DefaultNodeInfo): _58.DefaultNodeInfoAmino;
            fromAminoMsg(object: _58.DefaultNodeInfoAminoMsg): _58.DefaultNodeInfo;
            fromProtoMsg(message: _58.DefaultNodeInfoProtoMsg): _58.DefaultNodeInfo;
            toProto(message: _58.DefaultNodeInfo): Uint8Array;
            toProtoMsg(message: _58.DefaultNodeInfo): _58.DefaultNodeInfoProtoMsg;
        };
        DefaultNodeInfoOther: {
            encode(message: _58.DefaultNodeInfoOther, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _58.DefaultNodeInfoOther;
            fromPartial(object: any): _58.DefaultNodeInfoOther;
            fromAmino(object: _58.DefaultNodeInfoOtherAmino): _58.DefaultNodeInfoOther;
            toAmino(message: _58.DefaultNodeInfoOther): _58.DefaultNodeInfoOtherAmino;
            fromAminoMsg(object: _58.DefaultNodeInfoOtherAminoMsg): _58.DefaultNodeInfoOther;
            fromProtoMsg(message: _58.DefaultNodeInfoOtherProtoMsg): _58.DefaultNodeInfoOther;
            toProto(message: _58.DefaultNodeInfoOther): Uint8Array;
            toProtoMsg(message: _58.DefaultNodeInfoOther): _58.DefaultNodeInfoOtherProtoMsg;
        };
    };
    const types: {
        ValidatorSet: {
            encode(message: _63.ValidatorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _63.ValidatorSet;
            fromPartial(object: any): _63.ValidatorSet;
            fromAmino(object: _63.ValidatorSetAmino): _63.ValidatorSet;
            toAmino(message: _63.ValidatorSet): _63.ValidatorSetAmino;
            fromAminoMsg(object: _63.ValidatorSetAminoMsg): _63.ValidatorSet;
            fromProtoMsg(message: _63.ValidatorSetProtoMsg): _63.ValidatorSet;
            toProto(message: _63.ValidatorSet): Uint8Array;
            toProtoMsg(message: _63.ValidatorSet): _63.ValidatorSetProtoMsg;
        };
        Validator: {
            encode(message: _63.Validator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _63.Validator;
            fromPartial(object: any): _63.Validator;
            fromAmino(object: _63.ValidatorAmino): _63.Validator;
            toAmino(message: _63.Validator): _63.ValidatorAmino;
            fromAminoMsg(object: _63.ValidatorAminoMsg): _63.Validator;
            fromProtoMsg(message: _63.ValidatorProtoMsg): _63.Validator;
            toProto(message: _63.Validator): Uint8Array;
            toProtoMsg(message: _63.Validator): _63.ValidatorProtoMsg;
        };
        SimpleValidator: {
            encode(message: _63.SimpleValidator, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _63.SimpleValidator;
            fromPartial(object: any): _63.SimpleValidator;
            fromAmino(object: _63.SimpleValidatorAmino): _63.SimpleValidator;
            toAmino(message: _63.SimpleValidator): _63.SimpleValidatorAmino;
            fromAminoMsg(object: _63.SimpleValidatorAminoMsg): _63.SimpleValidator;
            fromProtoMsg(message: _63.SimpleValidatorProtoMsg): _63.SimpleValidator;
            toProto(message: _63.SimpleValidator): Uint8Array;
            toProtoMsg(message: _63.SimpleValidator): _63.SimpleValidatorProtoMsg;
        };
        blockIDFlagFromJSON(object: any): _62.BlockIDFlag;
        blockIDFlagToJSON(object: _62.BlockIDFlag): string;
        signedMsgTypeFromJSON(object: any): _62.SignedMsgType;
        signedMsgTypeToJSON(object: _62.SignedMsgType): string;
        BlockIDFlag: typeof _62.BlockIDFlag;
        BlockIDFlagSDKType: typeof _62.BlockIDFlag;
        BlockIDFlagAmino: typeof _62.BlockIDFlag;
        SignedMsgType: typeof _62.SignedMsgType;
        SignedMsgTypeSDKType: typeof _62.SignedMsgType;
        SignedMsgTypeAmino: typeof _62.SignedMsgType;
        PartSetHeader: {
            encode(message: _62.PartSetHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.PartSetHeader;
            fromPartial(object: any): _62.PartSetHeader;
            fromAmino(object: _62.PartSetHeaderAmino): _62.PartSetHeader;
            toAmino(message: _62.PartSetHeader): _62.PartSetHeaderAmino;
            fromAminoMsg(object: _62.PartSetHeaderAminoMsg): _62.PartSetHeader;
            fromProtoMsg(message: _62.PartSetHeaderProtoMsg): _62.PartSetHeader;
            toProto(message: _62.PartSetHeader): Uint8Array;
            toProtoMsg(message: _62.PartSetHeader): _62.PartSetHeaderProtoMsg;
        };
        Part: {
            encode(message: _62.Part, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.Part;
            fromPartial(object: any): _62.Part;
            fromAmino(object: _62.PartAmino): _62.Part;
            toAmino(message: _62.Part): _62.PartAmino;
            fromAminoMsg(object: _62.PartAminoMsg): _62.Part;
            fromProtoMsg(message: _62.PartProtoMsg): _62.Part;
            toProto(message: _62.Part): Uint8Array;
            toProtoMsg(message: _62.Part): _62.PartProtoMsg;
        };
        BlockID: {
            encode(message: _62.BlockID, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.BlockID;
            fromPartial(object: any): _62.BlockID;
            fromAmino(object: _62.BlockIDAmino): _62.BlockID;
            toAmino(message: _62.BlockID): _62.BlockIDAmino;
            fromAminoMsg(object: _62.BlockIDAminoMsg): _62.BlockID;
            fromProtoMsg(message: _62.BlockIDProtoMsg): _62.BlockID;
            toProto(message: _62.BlockID): Uint8Array;
            toProtoMsg(message: _62.BlockID): _62.BlockIDProtoMsg;
        };
        Header: {
            encode(message: _62.Header, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.Header;
            fromPartial(object: any): _62.Header;
            fromAmino(object: _62.HeaderAmino): _62.Header;
            toAmino(message: _62.Header): _62.HeaderAmino;
            fromAminoMsg(object: _62.HeaderAminoMsg): _62.Header;
            fromProtoMsg(message: _62.HeaderProtoMsg): _62.Header;
            toProto(message: _62.Header): Uint8Array;
            toProtoMsg(message: _62.Header): _62.HeaderProtoMsg;
        };
        Data: {
            encode(message: _62.Data, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.Data;
            fromPartial(object: any): _62.Data;
            fromAmino(object: _62.DataAmino): _62.Data;
            toAmino(message: _62.Data): _62.DataAmino;
            fromAminoMsg(object: _62.DataAminoMsg): _62.Data;
            fromProtoMsg(message: _62.DataProtoMsg): _62.Data;
            toProto(message: _62.Data): Uint8Array;
            toProtoMsg(message: _62.Data): _62.DataProtoMsg;
        };
        Vote: {
            encode(message: _62.Vote, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.Vote;
            fromPartial(object: any): _62.Vote;
            fromAmino(object: _62.VoteAmino): _62.Vote;
            toAmino(message: _62.Vote): _62.VoteAmino;
            fromAminoMsg(object: _62.VoteAminoMsg): _62.Vote;
            fromProtoMsg(message: _62.VoteProtoMsg): _62.Vote;
            toProto(message: _62.Vote): Uint8Array;
            toProtoMsg(message: _62.Vote): _62.VoteProtoMsg;
        };
        Commit: {
            encode(message: _62.Commit, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.Commit;
            fromPartial(object: any): _62.Commit;
            fromAmino(object: _62.CommitAmino): _62.Commit;
            toAmino(message: _62.Commit): _62.CommitAmino;
            fromAminoMsg(object: _62.CommitAminoMsg): _62.Commit;
            fromProtoMsg(message: _62.CommitProtoMsg): _62.Commit;
            toProto(message: _62.Commit): Uint8Array;
            toProtoMsg(message: _62.Commit): _62.CommitProtoMsg;
        };
        CommitSig: {
            encode(message: _62.CommitSig, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.CommitSig;
            fromPartial(object: any): _62.CommitSig;
            fromAmino(object: _62.CommitSigAmino): _62.CommitSig;
            toAmino(message: _62.CommitSig): _62.CommitSigAmino;
            fromAminoMsg(object: _62.CommitSigAminoMsg): _62.CommitSig;
            fromProtoMsg(message: _62.CommitSigProtoMsg): _62.CommitSig;
            toProto(message: _62.CommitSig): Uint8Array;
            toProtoMsg(message: _62.CommitSig): _62.CommitSigProtoMsg;
        };
        Proposal: {
            encode(message: _62.Proposal, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.Proposal;
            fromPartial(object: any): _62.Proposal;
            fromAmino(object: _62.ProposalAmino): _62.Proposal;
            toAmino(message: _62.Proposal): _62.ProposalAmino;
            fromAminoMsg(object: _62.ProposalAminoMsg): _62.Proposal;
            fromProtoMsg(message: _62.ProposalProtoMsg): _62.Proposal;
            toProto(message: _62.Proposal): Uint8Array;
            toProtoMsg(message: _62.Proposal): _62.ProposalProtoMsg;
        };
        SignedHeader: {
            encode(message: _62.SignedHeader, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.SignedHeader;
            fromPartial(object: any): _62.SignedHeader;
            fromAmino(object: _62.SignedHeaderAmino): _62.SignedHeader;
            toAmino(message: _62.SignedHeader): _62.SignedHeaderAmino;
            fromAminoMsg(object: _62.SignedHeaderAminoMsg): _62.SignedHeader;
            fromProtoMsg(message: _62.SignedHeaderProtoMsg): _62.SignedHeader;
            toProto(message: _62.SignedHeader): Uint8Array;
            toProtoMsg(message: _62.SignedHeader): _62.SignedHeaderProtoMsg;
        };
        LightBlock: {
            encode(message: _62.LightBlock, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.LightBlock;
            fromPartial(object: any): _62.LightBlock;
            fromAmino(object: _62.LightBlockAmino): _62.LightBlock;
            toAmino(message: _62.LightBlock): _62.LightBlockAmino;
            fromAminoMsg(object: _62.LightBlockAminoMsg): _62.LightBlock;
            fromProtoMsg(message: _62.LightBlockProtoMsg): _62.LightBlock;
            toProto(message: _62.LightBlock): Uint8Array;
            toProtoMsg(message: _62.LightBlock): _62.LightBlockProtoMsg;
        };
        BlockMeta: {
            encode(message: _62.BlockMeta, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.BlockMeta;
            fromPartial(object: any): _62.BlockMeta;
            fromAmino(object: _62.BlockMetaAmino): _62.BlockMeta;
            toAmino(message: _62.BlockMeta): _62.BlockMetaAmino;
            fromAminoMsg(object: _62.BlockMetaAminoMsg): _62.BlockMeta;
            fromProtoMsg(message: _62.BlockMetaProtoMsg): _62.BlockMeta;
            toProto(message: _62.BlockMeta): Uint8Array;
            toProtoMsg(message: _62.BlockMeta): _62.BlockMetaProtoMsg;
        };
        TxProof: {
            encode(message: _62.TxProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _62.TxProof;
            fromPartial(object: any): _62.TxProof;
            fromAmino(object: _62.TxProofAmino): _62.TxProof;
            toAmino(message: _62.TxProof): _62.TxProofAmino;
            fromAminoMsg(object: _62.TxProofAminoMsg): _62.TxProof;
            fromProtoMsg(message: _62.TxProofProtoMsg): _62.TxProof;
            toProto(message: _62.TxProof): Uint8Array;
            toProtoMsg(message: _62.TxProof): _62.TxProofProtoMsg;
        };
        ConsensusParams: {
            encode(message: _61.ConsensusParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _61.ConsensusParams;
            fromPartial(object: any): _61.ConsensusParams;
            fromAmino(object: _61.ConsensusParamsAmino): _61.ConsensusParams;
            toAmino(message: _61.ConsensusParams): _61.ConsensusParamsAmino;
            fromAminoMsg(object: _61.ConsensusParamsAminoMsg): _61.ConsensusParams;
            fromProtoMsg(message: _61.ConsensusParamsProtoMsg): _61.ConsensusParams;
            toProto(message: _61.ConsensusParams): Uint8Array;
            toProtoMsg(message: _61.ConsensusParams): _61.ConsensusParamsProtoMsg;
        };
        BlockParams: {
            encode(message: _61.BlockParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _61.BlockParams;
            fromPartial(object: any): _61.BlockParams;
            fromAmino(object: _61.BlockParamsAmino): _61.BlockParams;
            toAmino(message: _61.BlockParams): _61.BlockParamsAmino;
            fromAminoMsg(object: _61.BlockParamsAminoMsg): _61.BlockParams;
            fromProtoMsg(message: _61.BlockParamsProtoMsg): _61.BlockParams;
            toProto(message: _61.BlockParams): Uint8Array;
            toProtoMsg(message: _61.BlockParams): _61.BlockParamsProtoMsg;
        };
        EvidenceParams: {
            encode(message: _61.EvidenceParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _61.EvidenceParams;
            fromPartial(object: any): _61.EvidenceParams;
            fromAmino(object: _61.EvidenceParamsAmino): _61.EvidenceParams;
            toAmino(message: _61.EvidenceParams): _61.EvidenceParamsAmino;
            fromAminoMsg(object: _61.EvidenceParamsAminoMsg): _61.EvidenceParams;
            fromProtoMsg(message: _61.EvidenceParamsProtoMsg): _61.EvidenceParams;
            toProto(message: _61.EvidenceParams): Uint8Array;
            toProtoMsg(message: _61.EvidenceParams): _61.EvidenceParamsProtoMsg;
        };
        ValidatorParams: {
            encode(message: _61.ValidatorParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _61.ValidatorParams;
            fromPartial(object: any): _61.ValidatorParams;
            fromAmino(object: _61.ValidatorParamsAmino): _61.ValidatorParams;
            toAmino(message: _61.ValidatorParams): _61.ValidatorParamsAmino;
            fromAminoMsg(object: _61.ValidatorParamsAminoMsg): _61.ValidatorParams;
            fromProtoMsg(message: _61.ValidatorParamsProtoMsg): _61.ValidatorParams;
            toProto(message: _61.ValidatorParams): Uint8Array;
            toProtoMsg(message: _61.ValidatorParams): _61.ValidatorParamsProtoMsg;
        };
        VersionParams: {
            encode(message: _61.VersionParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _61.VersionParams;
            fromPartial(object: any): _61.VersionParams;
            fromAmino(object: _61.VersionParamsAmino): _61.VersionParams;
            toAmino(message: _61.VersionParams): _61.VersionParamsAmino;
            fromAminoMsg(object: _61.VersionParamsAminoMsg): _61.VersionParams;
            fromProtoMsg(message: _61.VersionParamsProtoMsg): _61.VersionParams;
            toProto(message: _61.VersionParams): Uint8Array;
            toProtoMsg(message: _61.VersionParams): _61.VersionParamsProtoMsg;
        };
        HashedParams: {
            encode(message: _61.HashedParams, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _61.HashedParams;
            fromPartial(object: any): _61.HashedParams;
            fromAmino(object: _61.HashedParamsAmino): _61.HashedParams;
            toAmino(message: _61.HashedParams): _61.HashedParamsAmino;
            fromAminoMsg(object: _61.HashedParamsAminoMsg): _61.HashedParams;
            fromProtoMsg(message: _61.HashedParamsProtoMsg): _61.HashedParams;
            toProto(message: _61.HashedParams): Uint8Array;
            toProtoMsg(message: _61.HashedParams): _61.HashedParamsProtoMsg;
        };
        Evidence: {
            encode(message: _60.Evidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _60.Evidence;
            fromPartial(object: any): _60.Evidence;
            fromAmino(object: _60.EvidenceAmino): _60.Evidence;
            toAmino(message: _60.Evidence): _60.EvidenceAmino;
            fromAminoMsg(object: _60.EvidenceAminoMsg): _60.Evidence;
            fromProtoMsg(message: _60.EvidenceProtoMsg): _60.Evidence;
            toProto(message: _60.Evidence): Uint8Array;
            toProtoMsg(message: _60.Evidence): _60.EvidenceProtoMsg;
        };
        DuplicateVoteEvidence: {
            encode(message: _60.DuplicateVoteEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _60.DuplicateVoteEvidence;
            fromPartial(object: any): _60.DuplicateVoteEvidence;
            fromAmino(object: _60.DuplicateVoteEvidenceAmino): _60.DuplicateVoteEvidence;
            toAmino(message: _60.DuplicateVoteEvidence): _60.DuplicateVoteEvidenceAmino;
            fromAminoMsg(object: _60.DuplicateVoteEvidenceAminoMsg): _60.DuplicateVoteEvidence;
            fromProtoMsg(message: _60.DuplicateVoteEvidenceProtoMsg): _60.DuplicateVoteEvidence;
            toProto(message: _60.DuplicateVoteEvidence): Uint8Array;
            toProtoMsg(message: _60.DuplicateVoteEvidence): _60.DuplicateVoteEvidenceProtoMsg;
        };
        LightClientAttackEvidence: {
            encode(message: _60.LightClientAttackEvidence, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _60.LightClientAttackEvidence;
            fromPartial(object: any): _60.LightClientAttackEvidence;
            fromAmino(object: _60.LightClientAttackEvidenceAmino): _60.LightClientAttackEvidence;
            toAmino(message: _60.LightClientAttackEvidence): _60.LightClientAttackEvidenceAmino;
            fromAminoMsg(object: _60.LightClientAttackEvidenceAminoMsg): _60.LightClientAttackEvidence;
            fromProtoMsg(message: _60.LightClientAttackEvidenceProtoMsg): _60.LightClientAttackEvidence;
            toProto(message: _60.LightClientAttackEvidence): Uint8Array;
            toProtoMsg(message: _60.LightClientAttackEvidence): _60.LightClientAttackEvidenceProtoMsg;
        };
        EvidenceList: {
            encode(message: _60.EvidenceList, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _60.EvidenceList;
            fromPartial(object: any): _60.EvidenceList;
            fromAmino(object: _60.EvidenceListAmino): _60.EvidenceList;
            toAmino(message: _60.EvidenceList): _60.EvidenceListAmino;
            fromAminoMsg(object: _60.EvidenceListAminoMsg): _60.EvidenceList;
            fromProtoMsg(message: _60.EvidenceListProtoMsg): _60.EvidenceList;
            toProto(message: _60.EvidenceList): Uint8Array;
            toProtoMsg(message: _60.EvidenceList): _60.EvidenceListProtoMsg;
        };
        Block: {
            encode(message: _59.Block, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _59.Block;
            fromPartial(object: any): _59.Block;
            fromAmino(object: _59.BlockAmino): _59.Block;
            toAmino(message: _59.Block): _59.BlockAmino;
            fromAminoMsg(object: _59.BlockAminoMsg): _59.Block;
            fromProtoMsg(message: _59.BlockProtoMsg): _59.Block;
            toProto(message: _59.Block): Uint8Array;
            toProtoMsg(message: _59.Block): _59.BlockProtoMsg;
        };
    };
    const version: {
        App: {
            encode(message: _64.App, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _64.App;
            fromPartial(object: any): _64.App;
            fromAmino(object: _64.AppAmino): _64.App;
            toAmino(message: _64.App): _64.AppAmino;
            fromAminoMsg(object: _64.AppAminoMsg): _64.App;
            fromProtoMsg(message: _64.AppProtoMsg): _64.App;
            toProto(message: _64.App): Uint8Array;
            toProtoMsg(message: _64.App): _64.AppProtoMsg;
        };
        Consensus: {
            encode(message: _64.Consensus, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _64.Consensus;
            fromPartial(object: any): _64.Consensus;
            fromAmino(object: _64.ConsensusAmino): _64.Consensus;
            toAmino(message: _64.Consensus): _64.ConsensusAmino;
            fromAminoMsg(object: _64.ConsensusAminoMsg): _64.Consensus;
            fromProtoMsg(message: _64.ConsensusProtoMsg): _64.Consensus;
            toProto(message: _64.Consensus): Uint8Array;
            toProtoMsg(message: _64.Consensus): _64.ConsensusProtoMsg;
        };
    };
}
