import * as _100 from "./protobuf/any";
import * as _101 from "./protobuf/descriptor";
import * as _102 from "./protobuf/duration";
import * as _103 from "./protobuf/empty";
import * as _104 from "./protobuf/timestamp";
export declare namespace google {
    const protobuf: {
        Timestamp: {
            encode(message: _104.Timestamp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _104.Timestamp;
            fromPartial(object: any): _104.Timestamp;
            fromAmino(object: string): _104.Timestamp;
            toAmino(message: _104.Timestamp): string;
            fromAminoMsg(object: _104.TimestampAminoMsg): _104.Timestamp;
            fromProtoMsg(message: _104.TimestampProtoMsg): _104.Timestamp;
            toProto(message: _104.Timestamp): Uint8Array;
            toProtoMsg(message: _104.Timestamp): _104.TimestampProtoMsg;
        };
        Empty: {
            encode(_: _103.Empty, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _103.Empty;
            fromPartial(_: any): _103.Empty;
            fromAmino(_: _103.EmptyAmino): _103.Empty;
            toAmino(_: _103.Empty): _103.EmptyAmino;
            fromAminoMsg(object: _103.EmptyAminoMsg): _103.Empty;
            fromProtoMsg(message: _103.EmptyProtoMsg): _103.Empty;
            toProto(message: _103.Empty): Uint8Array;
            toProtoMsg(message: _103.Empty): _103.EmptyProtoMsg;
        };
        Duration: {
            encode(message: _102.Duration, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _102.Duration;
            fromPartial(object: any): _102.Duration;
            fromAmino(object: string): _102.Duration;
            toAmino(message: _102.Duration): string;
            fromAminoMsg(object: _102.DurationAminoMsg): _102.Duration;
            fromProtoMsg(message: _102.DurationProtoMsg): _102.Duration;
            toProto(message: _102.Duration): Uint8Array;
            toProtoMsg(message: _102.Duration): _102.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _101.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _101.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _101.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _101.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _101.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _101.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _101.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _101.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _101.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _101.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _101.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _101.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _101.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _101.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _101.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _101.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _101.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _101.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _101.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _101.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _101.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _101.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _101.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _101.FieldOptions_CType;
        FieldOptions_JSType: typeof _101.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _101.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _101.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _101.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _101.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _101.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            encode(message: _101.FileDescriptorSet, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.FileDescriptorSet;
            fromPartial(object: any): _101.FileDescriptorSet;
            fromAmino(object: _101.FileDescriptorSetAmino): _101.FileDescriptorSet;
            toAmino(message: _101.FileDescriptorSet): _101.FileDescriptorSetAmino;
            fromAminoMsg(object: _101.FileDescriptorSetAminoMsg): _101.FileDescriptorSet;
            fromProtoMsg(message: _101.FileDescriptorSetProtoMsg): _101.FileDescriptorSet;
            toProto(message: _101.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _101.FileDescriptorSet): _101.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            encode(message: _101.FileDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.FileDescriptorProto;
            fromPartial(object: any): _101.FileDescriptorProto;
            fromAmino(object: _101.FileDescriptorProtoAmino): _101.FileDescriptorProto;
            toAmino(message: _101.FileDescriptorProto): _101.FileDescriptorProtoAmino;
            fromAminoMsg(object: _101.FileDescriptorProtoAminoMsg): _101.FileDescriptorProto;
            fromProtoMsg(message: _101.FileDescriptorProtoProtoMsg): _101.FileDescriptorProto;
            toProto(message: _101.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.FileDescriptorProto): _101.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            encode(message: _101.DescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.DescriptorProto;
            fromPartial(object: any): _101.DescriptorProto;
            fromAmino(object: _101.DescriptorProtoAmino): _101.DescriptorProto;
            toAmino(message: _101.DescriptorProto): _101.DescriptorProtoAmino;
            fromAminoMsg(object: _101.DescriptorProtoAminoMsg): _101.DescriptorProto;
            fromProtoMsg(message: _101.DescriptorProtoProtoMsg): _101.DescriptorProto;
            toProto(message: _101.DescriptorProto): Uint8Array;
            toProtoMsg(message: _101.DescriptorProto): _101.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            encode(message: _101.DescriptorProto_ExtensionRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.DescriptorProto_ExtensionRange;
            fromPartial(object: any): _101.DescriptorProto_ExtensionRange;
            fromAmino(object: _101.DescriptorProto_ExtensionRangeAmino): _101.DescriptorProto_ExtensionRange;
            toAmino(message: _101.DescriptorProto_ExtensionRange): _101.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _101.DescriptorProto_ExtensionRangeAminoMsg): _101.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _101.DescriptorProto_ExtensionRangeProtoMsg): _101.DescriptorProto_ExtensionRange;
            toProto(message: _101.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _101.DescriptorProto_ExtensionRange): _101.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            encode(message: _101.DescriptorProto_ReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.DescriptorProto_ReservedRange;
            fromPartial(object: any): _101.DescriptorProto_ReservedRange;
            fromAmino(object: _101.DescriptorProto_ReservedRangeAmino): _101.DescriptorProto_ReservedRange;
            toAmino(message: _101.DescriptorProto_ReservedRange): _101.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _101.DescriptorProto_ReservedRangeAminoMsg): _101.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _101.DescriptorProto_ReservedRangeProtoMsg): _101.DescriptorProto_ReservedRange;
            toProto(message: _101.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _101.DescriptorProto_ReservedRange): _101.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            encode(message: _101.ExtensionRangeOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.ExtensionRangeOptions;
            fromPartial(object: any): _101.ExtensionRangeOptions;
            fromAmino(object: _101.ExtensionRangeOptionsAmino): _101.ExtensionRangeOptions;
            toAmino(message: _101.ExtensionRangeOptions): _101.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _101.ExtensionRangeOptionsAminoMsg): _101.ExtensionRangeOptions;
            fromProtoMsg(message: _101.ExtensionRangeOptionsProtoMsg): _101.ExtensionRangeOptions;
            toProto(message: _101.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _101.ExtensionRangeOptions): _101.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            encode(message: _101.FieldDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.FieldDescriptorProto;
            fromPartial(object: any): _101.FieldDescriptorProto;
            fromAmino(object: _101.FieldDescriptorProtoAmino): _101.FieldDescriptorProto;
            toAmino(message: _101.FieldDescriptorProto): _101.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _101.FieldDescriptorProtoAminoMsg): _101.FieldDescriptorProto;
            fromProtoMsg(message: _101.FieldDescriptorProtoProtoMsg): _101.FieldDescriptorProto;
            toProto(message: _101.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.FieldDescriptorProto): _101.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            encode(message: _101.OneofDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.OneofDescriptorProto;
            fromPartial(object: any): _101.OneofDescriptorProto;
            fromAmino(object: _101.OneofDescriptorProtoAmino): _101.OneofDescriptorProto;
            toAmino(message: _101.OneofDescriptorProto): _101.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _101.OneofDescriptorProtoAminoMsg): _101.OneofDescriptorProto;
            fromProtoMsg(message: _101.OneofDescriptorProtoProtoMsg): _101.OneofDescriptorProto;
            toProto(message: _101.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.OneofDescriptorProto): _101.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            encode(message: _101.EnumDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.EnumDescriptorProto;
            fromPartial(object: any): _101.EnumDescriptorProto;
            fromAmino(object: _101.EnumDescriptorProtoAmino): _101.EnumDescriptorProto;
            toAmino(message: _101.EnumDescriptorProto): _101.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _101.EnumDescriptorProtoAminoMsg): _101.EnumDescriptorProto;
            fromProtoMsg(message: _101.EnumDescriptorProtoProtoMsg): _101.EnumDescriptorProto;
            toProto(message: _101.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.EnumDescriptorProto): _101.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            encode(message: _101.EnumDescriptorProto_EnumReservedRange, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: any): _101.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _101.EnumDescriptorProto_EnumReservedRangeAmino): _101.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _101.EnumDescriptorProto_EnumReservedRange): _101.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _101.EnumDescriptorProto_EnumReservedRangeAminoMsg): _101.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _101.EnumDescriptorProto_EnumReservedRangeProtoMsg): _101.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _101.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _101.EnumDescriptorProto_EnumReservedRange): _101.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            encode(message: _101.EnumValueDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.EnumValueDescriptorProto;
            fromPartial(object: any): _101.EnumValueDescriptorProto;
            fromAmino(object: _101.EnumValueDescriptorProtoAmino): _101.EnumValueDescriptorProto;
            toAmino(message: _101.EnumValueDescriptorProto): _101.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _101.EnumValueDescriptorProtoAminoMsg): _101.EnumValueDescriptorProto;
            fromProtoMsg(message: _101.EnumValueDescriptorProtoProtoMsg): _101.EnumValueDescriptorProto;
            toProto(message: _101.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.EnumValueDescriptorProto): _101.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            encode(message: _101.ServiceDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.ServiceDescriptorProto;
            fromPartial(object: any): _101.ServiceDescriptorProto;
            fromAmino(object: _101.ServiceDescriptorProtoAmino): _101.ServiceDescriptorProto;
            toAmino(message: _101.ServiceDescriptorProto): _101.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _101.ServiceDescriptorProtoAminoMsg): _101.ServiceDescriptorProto;
            fromProtoMsg(message: _101.ServiceDescriptorProtoProtoMsg): _101.ServiceDescriptorProto;
            toProto(message: _101.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.ServiceDescriptorProto): _101.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            encode(message: _101.MethodDescriptorProto, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.MethodDescriptorProto;
            fromPartial(object: any): _101.MethodDescriptorProto;
            fromAmino(object: _101.MethodDescriptorProtoAmino): _101.MethodDescriptorProto;
            toAmino(message: _101.MethodDescriptorProto): _101.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _101.MethodDescriptorProtoAminoMsg): _101.MethodDescriptorProto;
            fromProtoMsg(message: _101.MethodDescriptorProtoProtoMsg): _101.MethodDescriptorProto;
            toProto(message: _101.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _101.MethodDescriptorProto): _101.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            encode(message: _101.FileOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.FileOptions;
            fromPartial(object: any): _101.FileOptions;
            fromAmino(object: _101.FileOptionsAmino): _101.FileOptions;
            toAmino(message: _101.FileOptions): _101.FileOptionsAmino;
            fromAminoMsg(object: _101.FileOptionsAminoMsg): _101.FileOptions;
            fromProtoMsg(message: _101.FileOptionsProtoMsg): _101.FileOptions;
            toProto(message: _101.FileOptions): Uint8Array;
            toProtoMsg(message: _101.FileOptions): _101.FileOptionsProtoMsg;
        };
        MessageOptions: {
            encode(message: _101.MessageOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.MessageOptions;
            fromPartial(object: any): _101.MessageOptions;
            fromAmino(object: _101.MessageOptionsAmino): _101.MessageOptions;
            toAmino(message: _101.MessageOptions): _101.MessageOptionsAmino;
            fromAminoMsg(object: _101.MessageOptionsAminoMsg): _101.MessageOptions;
            fromProtoMsg(message: _101.MessageOptionsProtoMsg): _101.MessageOptions;
            toProto(message: _101.MessageOptions): Uint8Array;
            toProtoMsg(message: _101.MessageOptions): _101.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            encode(message: _101.FieldOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.FieldOptions;
            fromPartial(object: any): _101.FieldOptions;
            fromAmino(object: _101.FieldOptionsAmino): _101.FieldOptions;
            toAmino(message: _101.FieldOptions): _101.FieldOptionsAmino;
            fromAminoMsg(object: _101.FieldOptionsAminoMsg): _101.FieldOptions;
            fromProtoMsg(message: _101.FieldOptionsProtoMsg): _101.FieldOptions;
            toProto(message: _101.FieldOptions): Uint8Array;
            toProtoMsg(message: _101.FieldOptions): _101.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            encode(message: _101.OneofOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.OneofOptions;
            fromPartial(object: any): _101.OneofOptions;
            fromAmino(object: _101.OneofOptionsAmino): _101.OneofOptions;
            toAmino(message: _101.OneofOptions): _101.OneofOptionsAmino;
            fromAminoMsg(object: _101.OneofOptionsAminoMsg): _101.OneofOptions;
            fromProtoMsg(message: _101.OneofOptionsProtoMsg): _101.OneofOptions;
            toProto(message: _101.OneofOptions): Uint8Array;
            toProtoMsg(message: _101.OneofOptions): _101.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            encode(message: _101.EnumOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.EnumOptions;
            fromPartial(object: any): _101.EnumOptions;
            fromAmino(object: _101.EnumOptionsAmino): _101.EnumOptions;
            toAmino(message: _101.EnumOptions): _101.EnumOptionsAmino;
            fromAminoMsg(object: _101.EnumOptionsAminoMsg): _101.EnumOptions;
            fromProtoMsg(message: _101.EnumOptionsProtoMsg): _101.EnumOptions;
            toProto(message: _101.EnumOptions): Uint8Array;
            toProtoMsg(message: _101.EnumOptions): _101.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            encode(message: _101.EnumValueOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.EnumValueOptions;
            fromPartial(object: any): _101.EnumValueOptions;
            fromAmino(object: _101.EnumValueOptionsAmino): _101.EnumValueOptions;
            toAmino(message: _101.EnumValueOptions): _101.EnumValueOptionsAmino;
            fromAminoMsg(object: _101.EnumValueOptionsAminoMsg): _101.EnumValueOptions;
            fromProtoMsg(message: _101.EnumValueOptionsProtoMsg): _101.EnumValueOptions;
            toProto(message: _101.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _101.EnumValueOptions): _101.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            encode(message: _101.ServiceOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.ServiceOptions;
            fromPartial(object: any): _101.ServiceOptions;
            fromAmino(object: _101.ServiceOptionsAmino): _101.ServiceOptions;
            toAmino(message: _101.ServiceOptions): _101.ServiceOptionsAmino;
            fromAminoMsg(object: _101.ServiceOptionsAminoMsg): _101.ServiceOptions;
            fromProtoMsg(message: _101.ServiceOptionsProtoMsg): _101.ServiceOptions;
            toProto(message: _101.ServiceOptions): Uint8Array;
            toProtoMsg(message: _101.ServiceOptions): _101.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            encode(message: _101.MethodOptions, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.MethodOptions;
            fromPartial(object: any): _101.MethodOptions;
            fromAmino(object: _101.MethodOptionsAmino): _101.MethodOptions;
            toAmino(message: _101.MethodOptions): _101.MethodOptionsAmino;
            fromAminoMsg(object: _101.MethodOptionsAminoMsg): _101.MethodOptions;
            fromProtoMsg(message: _101.MethodOptionsProtoMsg): _101.MethodOptions;
            toProto(message: _101.MethodOptions): Uint8Array;
            toProtoMsg(message: _101.MethodOptions): _101.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            encode(message: _101.UninterpretedOption, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.UninterpretedOption;
            fromPartial(object: any): _101.UninterpretedOption;
            fromAmino(object: _101.UninterpretedOptionAmino): _101.UninterpretedOption;
            toAmino(message: _101.UninterpretedOption): _101.UninterpretedOptionAmino;
            fromAminoMsg(object: _101.UninterpretedOptionAminoMsg): _101.UninterpretedOption;
            fromProtoMsg(message: _101.UninterpretedOptionProtoMsg): _101.UninterpretedOption;
            toProto(message: _101.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _101.UninterpretedOption): _101.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            encode(message: _101.UninterpretedOption_NamePart, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.UninterpretedOption_NamePart;
            fromPartial(object: any): _101.UninterpretedOption_NamePart;
            fromAmino(object: _101.UninterpretedOption_NamePartAmino): _101.UninterpretedOption_NamePart;
            toAmino(message: _101.UninterpretedOption_NamePart): _101.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _101.UninterpretedOption_NamePartAminoMsg): _101.UninterpretedOption_NamePart;
            fromProtoMsg(message: _101.UninterpretedOption_NamePartProtoMsg): _101.UninterpretedOption_NamePart;
            toProto(message: _101.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _101.UninterpretedOption_NamePart): _101.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            encode(message: _101.SourceCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.SourceCodeInfo;
            fromPartial(object: any): _101.SourceCodeInfo;
            fromAmino(object: _101.SourceCodeInfoAmino): _101.SourceCodeInfo;
            toAmino(message: _101.SourceCodeInfo): _101.SourceCodeInfoAmino;
            fromAminoMsg(object: _101.SourceCodeInfoAminoMsg): _101.SourceCodeInfo;
            fromProtoMsg(message: _101.SourceCodeInfoProtoMsg): _101.SourceCodeInfo;
            toProto(message: _101.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _101.SourceCodeInfo): _101.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            encode(message: _101.SourceCodeInfo_Location, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.SourceCodeInfo_Location;
            fromPartial(object: any): _101.SourceCodeInfo_Location;
            fromAmino(object: _101.SourceCodeInfo_LocationAmino): _101.SourceCodeInfo_Location;
            toAmino(message: _101.SourceCodeInfo_Location): _101.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _101.SourceCodeInfo_LocationAminoMsg): _101.SourceCodeInfo_Location;
            fromProtoMsg(message: _101.SourceCodeInfo_LocationProtoMsg): _101.SourceCodeInfo_Location;
            toProto(message: _101.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _101.SourceCodeInfo_Location): _101.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            encode(message: _101.GeneratedCodeInfo, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.GeneratedCodeInfo;
            fromPartial(object: any): _101.GeneratedCodeInfo;
            fromAmino(object: _101.GeneratedCodeInfoAmino): _101.GeneratedCodeInfo;
            toAmino(message: _101.GeneratedCodeInfo): _101.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _101.GeneratedCodeInfoAminoMsg): _101.GeneratedCodeInfo;
            fromProtoMsg(message: _101.GeneratedCodeInfoProtoMsg): _101.GeneratedCodeInfo;
            toProto(message: _101.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _101.GeneratedCodeInfo): _101.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            encode(message: _101.GeneratedCodeInfo_Annotation, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _101.GeneratedCodeInfo_Annotation;
            fromPartial(object: any): _101.GeneratedCodeInfo_Annotation;
            fromAmino(object: _101.GeneratedCodeInfo_AnnotationAmino): _101.GeneratedCodeInfo_Annotation;
            toAmino(message: _101.GeneratedCodeInfo_Annotation): _101.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _101.GeneratedCodeInfo_AnnotationAminoMsg): _101.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _101.GeneratedCodeInfo_AnnotationProtoMsg): _101.GeneratedCodeInfo_Annotation;
            toProto(message: _101.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _101.GeneratedCodeInfo_Annotation): _101.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            encode(message: _100.Any, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
            decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _100.Any;
            fromPartial(object: any): _100.Any;
            fromAmino(object: _100.AnyAmino): _100.Any;
            toAmino(message: _100.Any): _100.AnyAmino;
            fromAminoMsg(object: _100.AnyAminoMsg): _100.Any;
            fromProtoMsg(message: _100.AnyProtoMsg): _100.Any;
            toProto(message: _100.Any): Uint8Array;
            toProtoMsg(message: _100.Any): _100.AnyProtoMsg;
        };
    };
}
