import * as _96 from "../confio/proofs";
export declare const ics23: {
    hashOpFromJSON(object: any): _96.HashOp;
    hashOpToJSON(object: _96.HashOp): string;
    lengthOpFromJSON(object: any): _96.LengthOp;
    lengthOpToJSON(object: _96.LengthOp): string;
    HashOp: typeof _96.HashOp;
    HashOpSDKType: typeof _96.HashOp;
    HashOpAmino: typeof _96.HashOp;
    LengthOp: typeof _96.LengthOp;
    LengthOpSDKType: typeof _96.LengthOp;
    LengthOpAmino: typeof _96.LengthOp;
    ExistenceProof: {
        encode(message: _96.ExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.ExistenceProof;
        fromPartial(object: any): _96.ExistenceProof;
        fromAmino(object: _96.ExistenceProofAmino): _96.ExistenceProof;
        toAmino(message: _96.ExistenceProof): _96.ExistenceProofAmino;
        fromAminoMsg(object: _96.ExistenceProofAminoMsg): _96.ExistenceProof;
        fromProtoMsg(message: _96.ExistenceProofProtoMsg): _96.ExistenceProof;
        toProto(message: _96.ExistenceProof): Uint8Array;
        toProtoMsg(message: _96.ExistenceProof): _96.ExistenceProofProtoMsg;
    };
    NonExistenceProof: {
        encode(message: _96.NonExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.NonExistenceProof;
        fromPartial(object: any): _96.NonExistenceProof;
        fromAmino(object: _96.NonExistenceProofAmino): _96.NonExistenceProof;
        toAmino(message: _96.NonExistenceProof): _96.NonExistenceProofAmino;
        fromAminoMsg(object: _96.NonExistenceProofAminoMsg): _96.NonExistenceProof;
        fromProtoMsg(message: _96.NonExistenceProofProtoMsg): _96.NonExistenceProof;
        toProto(message: _96.NonExistenceProof): Uint8Array;
        toProtoMsg(message: _96.NonExistenceProof): _96.NonExistenceProofProtoMsg;
    };
    CommitmentProof: {
        encode(message: _96.CommitmentProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.CommitmentProof;
        fromPartial(object: any): _96.CommitmentProof;
        fromAmino(object: _96.CommitmentProofAmino): _96.CommitmentProof;
        toAmino(message: _96.CommitmentProof): _96.CommitmentProofAmino;
        fromAminoMsg(object: _96.CommitmentProofAminoMsg): _96.CommitmentProof;
        fromProtoMsg(message: _96.CommitmentProofProtoMsg): _96.CommitmentProof;
        toProto(message: _96.CommitmentProof): Uint8Array;
        toProtoMsg(message: _96.CommitmentProof): _96.CommitmentProofProtoMsg;
    };
    LeafOp: {
        encode(message: _96.LeafOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.LeafOp;
        fromPartial(object: any): _96.LeafOp;
        fromAmino(object: _96.LeafOpAmino): _96.LeafOp;
        toAmino(message: _96.LeafOp): _96.LeafOpAmino;
        fromAminoMsg(object: _96.LeafOpAminoMsg): _96.LeafOp;
        fromProtoMsg(message: _96.LeafOpProtoMsg): _96.LeafOp;
        toProto(message: _96.LeafOp): Uint8Array;
        toProtoMsg(message: _96.LeafOp): _96.LeafOpProtoMsg;
    };
    InnerOp: {
        encode(message: _96.InnerOp, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.InnerOp;
        fromPartial(object: any): _96.InnerOp;
        fromAmino(object: _96.InnerOpAmino): _96.InnerOp;
        toAmino(message: _96.InnerOp): _96.InnerOpAmino;
        fromAminoMsg(object: _96.InnerOpAminoMsg): _96.InnerOp;
        fromProtoMsg(message: _96.InnerOpProtoMsg): _96.InnerOp;
        toProto(message: _96.InnerOp): Uint8Array;
        toProtoMsg(message: _96.InnerOp): _96.InnerOpProtoMsg;
    };
    ProofSpec: {
        encode(message: _96.ProofSpec, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.ProofSpec;
        fromPartial(object: any): _96.ProofSpec;
        fromAmino(object: _96.ProofSpecAmino): _96.ProofSpec;
        toAmino(message: _96.ProofSpec): _96.ProofSpecAmino;
        fromAminoMsg(object: _96.ProofSpecAminoMsg): _96.ProofSpec;
        fromProtoMsg(message: _96.ProofSpecProtoMsg): _96.ProofSpec;
        toProto(message: _96.ProofSpec): Uint8Array;
        toProtoMsg(message: _96.ProofSpec): _96.ProofSpecProtoMsg;
    };
    InnerSpec: {
        encode(message: _96.InnerSpec, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.InnerSpec;
        fromPartial(object: any): _96.InnerSpec;
        fromAmino(object: _96.InnerSpecAmino): _96.InnerSpec;
        toAmino(message: _96.InnerSpec): _96.InnerSpecAmino;
        fromAminoMsg(object: _96.InnerSpecAminoMsg): _96.InnerSpec;
        fromProtoMsg(message: _96.InnerSpecProtoMsg): _96.InnerSpec;
        toProto(message: _96.InnerSpec): Uint8Array;
        toProtoMsg(message: _96.InnerSpec): _96.InnerSpecProtoMsg;
    };
    BatchProof: {
        encode(message: _96.BatchProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.BatchProof;
        fromPartial(object: any): _96.BatchProof;
        fromAmino(object: _96.BatchProofAmino): _96.BatchProof;
        toAmino(message: _96.BatchProof): _96.BatchProofAmino;
        fromAminoMsg(object: _96.BatchProofAminoMsg): _96.BatchProof;
        fromProtoMsg(message: _96.BatchProofProtoMsg): _96.BatchProof;
        toProto(message: _96.BatchProof): Uint8Array;
        toProtoMsg(message: _96.BatchProof): _96.BatchProofProtoMsg;
    };
    BatchEntry: {
        encode(message: _96.BatchEntry, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.BatchEntry;
        fromPartial(object: any): _96.BatchEntry;
        fromAmino(object: _96.BatchEntryAmino): _96.BatchEntry;
        toAmino(message: _96.BatchEntry): _96.BatchEntryAmino;
        fromAminoMsg(object: _96.BatchEntryAminoMsg): _96.BatchEntry;
        fromProtoMsg(message: _96.BatchEntryProtoMsg): _96.BatchEntry;
        toProto(message: _96.BatchEntry): Uint8Array;
        toProtoMsg(message: _96.BatchEntry): _96.BatchEntryProtoMsg;
    };
    CompressedBatchProof: {
        encode(message: _96.CompressedBatchProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.CompressedBatchProof;
        fromPartial(object: any): _96.CompressedBatchProof;
        fromAmino(object: _96.CompressedBatchProofAmino): _96.CompressedBatchProof;
        toAmino(message: _96.CompressedBatchProof): _96.CompressedBatchProofAmino;
        fromAminoMsg(object: _96.CompressedBatchProofAminoMsg): _96.CompressedBatchProof;
        fromProtoMsg(message: _96.CompressedBatchProofProtoMsg): _96.CompressedBatchProof;
        toProto(message: _96.CompressedBatchProof): Uint8Array;
        toProtoMsg(message: _96.CompressedBatchProof): _96.CompressedBatchProofProtoMsg;
    };
    CompressedBatchEntry: {
        encode(message: _96.CompressedBatchEntry, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.CompressedBatchEntry;
        fromPartial(object: any): _96.CompressedBatchEntry;
        fromAmino(object: _96.CompressedBatchEntryAmino): _96.CompressedBatchEntry;
        toAmino(message: _96.CompressedBatchEntry): _96.CompressedBatchEntryAmino;
        fromAminoMsg(object: _96.CompressedBatchEntryAminoMsg): _96.CompressedBatchEntry;
        fromProtoMsg(message: _96.CompressedBatchEntryProtoMsg): _96.CompressedBatchEntry;
        toProto(message: _96.CompressedBatchEntry): Uint8Array;
        toProtoMsg(message: _96.CompressedBatchEntry): _96.CompressedBatchEntryProtoMsg;
    };
    CompressedExistenceProof: {
        encode(message: _96.CompressedExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.CompressedExistenceProof;
        fromPartial(object: any): _96.CompressedExistenceProof;
        fromAmino(object: _96.CompressedExistenceProofAmino): _96.CompressedExistenceProof;
        toAmino(message: _96.CompressedExistenceProof): _96.CompressedExistenceProofAmino;
        fromAminoMsg(object: _96.CompressedExistenceProofAminoMsg): _96.CompressedExistenceProof;
        fromProtoMsg(message: _96.CompressedExistenceProofProtoMsg): _96.CompressedExistenceProof;
        toProto(message: _96.CompressedExistenceProof): Uint8Array;
        toProtoMsg(message: _96.CompressedExistenceProof): _96.CompressedExistenceProofProtoMsg;
    };
    CompressedNonExistenceProof: {
        encode(message: _96.CompressedNonExistenceProof, writer?: import("protobufjs").Writer): import("protobufjs").Writer;
        decode(input: Uint8Array | import("protobufjs").Reader, length?: number): _96.CompressedNonExistenceProof;
        fromPartial(object: any): _96.CompressedNonExistenceProof;
        fromAmino(object: _96.CompressedNonExistenceProofAmino): _96.CompressedNonExistenceProof;
        toAmino(message: _96.CompressedNonExistenceProof): _96.CompressedNonExistenceProofAmino;
        fromAminoMsg(object: _96.CompressedNonExistenceProofAminoMsg): _96.CompressedNonExistenceProof;
        fromProtoMsg(message: _96.CompressedNonExistenceProofProtoMsg): _96.CompressedNonExistenceProof;
        toProto(message: _96.CompressedNonExistenceProof): Uint8Array;
        toProtoMsg(message: _96.CompressedNonExistenceProof): _96.CompressedNonExistenceProofProtoMsg;
    };
};
